name: Execute Terratest
on: [push]

jobs:
  execute-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        # terraform_wrapper: false is used to bypass issue #706
        # https://github.com/gruntwork-io/terratest/issues/706#issuecomment-733495166
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0
          terraform_wrapper: false
      - name: Set up Golang
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - id: go-cache-paths
        run: |
          echo "::set-output name=go-build::$(go env GOCACHE)"
          echo "::set-output name=go-mod::$(go env GOMODCACHE)"
      # Cache go build cache, used to speedup go test
      - name: Go Build Cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.go-cache-paths.outputs.go-build }}
          key: ${{ runner.os }}-go-build-${{ hashFiles('**/go.sum') }}

      # Cache go mod cache, used to speedup builds
      - name: Go Mod Cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.go-cache-paths.outputs.go-mod }}
          key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.sum') }}
      - name: Run Test
        run: |
          cd test
          go test -v